[package]
name = "rust_pong"
version = "0.1.0"
authors = ["Wonhyuk Choi <wc012013@mymail.pomona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
